### ISSUE TITLE
Pre-File window not appearing

### ISSUE THREAD

**Issue by LightRO** [3dash/xACARS#8]
Hello Everyone,

when i click on Pre-File then opens a new Window with the title TK and this window is clear. So i can't select the next steps.

![image](https://user-images.githubusercontent.com/19392688/109415132-29ab4b80-79b7-11eb-8533-43ee8a6b2396.png)

Can you help me here?

Best Regards,
LightRO

**Comment by hcshires** [comment]
This has been fixed in v2, however, there's not a release yet. You can download v2 here: https://github.com/hcshires/xACARS/releases/tag/v2.0.0

**Comment by hcshires** [comment]
This issue refers to #4 which has been fixed

**Comment by slimit75** [comment]
Ill double check and release the version with the fix soon, maybe later today

**Comment by slimit75** [comment]
Sorry for the delay, ill have a chance tonight to get it released.

**Comment by slimit75** [comment]
Only took me 2 or 3 months to release but its out
